/**
 * This file is auto-generated by scripts/generateSchema.ts
 * Do not edit manually
 */
export interface components {
  schemas: {
    /** @description demo */
    demo: {
      /**
       * Format: date-time
       * @description 时间
       */
      ts?: string;
    };
  };
}
