/**
 * This file is auto-generated by scripts/generateSchema.ts
 * Do not edit manually
 */
import { components as generated } from '@/api/generated'
import { components } from '@/api/schema'

/** Runtime representation of OpenAPI Schemas */
export const schemas = {
  AggregateException: {
    innerExceptions: {
      type: '{ targetSite?: unknown; message?: string | null | undefined; data?: Record<string, never> | null | undefined; innerException?: any | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; }[] | null | undefined',
    },
    message: {
      type: 'string | null | undefined',
    },
    targetSite: {
      type: 'unknown',
    },
    data: {
      type: 'Record<string, never> | null | undefined',
    },
    innerException: {
      type: '{ targetSite?: unknown; message?: string | null | undefined; data?: Record<string, never> | null | undefined; innerException?: any | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; } | undefined',
    },
    helpLink: {
      type: 'string | null | undefined',
    },
    source: {
      type: 'string | null | undefined',
    },
    hResult: {
      type: 'string | number | undefined',
      format: 'int32',
    },
    stackTrace: {
      type: 'string | null | undefined',
    },
  },
  ChatMessage: {
    role: {
      type: 'string | undefined',
      description: '角色 (user, assistant, system)',
    },
    content: {
      type: 'string | undefined',
      description: '内容',
    },
  },
  CollectedMedia: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    startTime: {
      type: 'string | undefined',
      description: '开始处理时间',
      format: 'date-time',
    },
    endTime: {
      type: 'string | null | undefined',
      description: '结束处理时间',
      format: 'date-time',
    },
    originalPath: {
      type: 'string | undefined',
      description: '原始路径',
    },
    savePath: {
      type: 'string | undefined',
      description: '保存路径',
    },
    fileSize: {
      type: 'string | number | undefined',
      description: '文件大小',
      format: 'int64',
    },
    fileType: {
      type: 'string | undefined',
      description: '文件类型',
    },
    series: {
      type: 'string | undefined',
      description: '系列',
    },
    episode: {
      type: 'string | undefined',
      description: '集数',
    },
  },
  CoverageSeason: {
    name: {
      type: 'string | undefined',
      description: '季名称',
    },
    episodeCoverage: {
      type: '{ [key: string]: boolean; } | undefined',
      description: '集数覆盖率，键为集数，值为是否覆盖',
    },
  },
  CustomConditionalType: {},
  CustomOrderByType: {},
  DanmuCoverage: {
    series: {
      type: 'string | undefined',
      description: '系列',
    },
    seasons: {
      type: '{ name?: string | undefined; episodeCoverage?: { [key: string]: boolean; } | undefined; }[] | undefined',
      description: '季覆盖率列表',
    },
  },
  DownloadTask: {
    media: {
      type: '{ id?: string | number | undefined; startTime?: string | undefined; endTime?: string | null | undefined; originalPath?: string | undefined; savePath?: string | undefined; fileSize?: string | number | undefined; fileType?: string | undefined; series?: string | undefined; episode?: string | undefined; }',
      description: '媒体信息',
    },
    series: {
      type: '{ id?: string | number | undefined; title?: string | undefined; path?: string | undefined; } | null | undefined',
    },
    currentTask: {
      type: '{ id?: string | number | undefined; exception?: { innerExceptions?: { targetSite?: unknown; message?: string | null | undefined; data?: Record<string, never> | null | undefined; innerException?: any | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; }[] | null | undefined; message?: string | null | undefined; targetSite?: unknown; data?: Record<string, never> | null | undefined; innerException?: { targetSite?: unknown; message?: string | null | undefined; data?: Record<string, never> | null | undefined; innerException?: any | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; } | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; } | undefined; status?: number | undefined; isCanceled?: boolean | undefined; isCompleted?: boolean | undefined; isCompletedSuccessfully?: boolean | undefined; creationOptions?: number | undefined; asyncState?: unknown; isFaulted?: boolean | undefined; } | null | undefined',
    },
    status: {
      type: 'number | undefined',
      description: '任务状态',
    },
    progress: {
      type: 'string | number',
      description: '下载进度',
      format: 'double',
    },
  },
  Exception: {
    targetSite: {
      type: 'unknown',
    },
    message: {
      type: 'string | null | undefined',
    },
    data: {
      type: 'Record<string, never> | null | undefined',
    },
    innerException: {
      type: '{ targetSite?: unknown; message?: string | null | undefined; data?: Record<string, never> | null | undefined; innerException?: any | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; } | undefined',
    },
    helpLink: {
      type: 'string | null | undefined',
    },
    source: {
      type: 'string | null | undefined',
    },
    hResult: {
      type: 'string | number | undefined',
      format: 'int32',
    },
    stackTrace: {
      type: 'string | null | undefined',
    },
  },
  ExecuteRenameRequest: {
    targetDir: {
      type: 'string | undefined',
      description: '目标目录',
    },
    items: {
      type: '{ oldName?: string | undefined; newName?: string | undefined; status?: string | undefined; }[] | undefined',
      description: '需要重命名的文件列表',
    },
  },
  IFormFile: {},
  MessageCode: {
    codeIndex: {
      type: 'string | undefined',
    },
    code: {
      type: 'string | undefined',
    },
    args: {
      type: 'unknown[] | null',
    },
    message: {
      type: 'string | undefined',
    },
  },
  MessageCodeEnum: {},
  MethodBase: {},
  PagedResultOfCollectedMedia: {
    items: {
      type: '{ id?: string | number | undefined; startTime?: string | undefined; endTime?: string | null | undefined; originalPath?: string | undefined; savePath?: string | undefined; fileSize?: string | number | undefined; fileType?: string | undefined; series?: string | undefined; episode?: string | undefined; }[]',
      description: '当前页的数据列表',
    },
    totalCount: {
      type: 'string | number',
      description: '数据总条数',
      format: 'int32',
    },
    pageNumber: {
      type: 'string | number',
      description: '当前页码',
      format: 'int32',
    },
    pageSize: {
      type: 'string | number',
      description: '每页大小',
      format: 'int32',
    },
    totalPages: {
      type: 'string | number | undefined',
      description: '总页数',
      format: 'int32',
    },
    hasPreviousPage: {
      type: 'boolean | undefined',
      description: '是否有上一页',
    },
    hasNextPage: {
      type: 'boolean | undefined',
      description: '是否有下一页',
    },
  },
  PendingSeries: {
    medias: {
      type: '{ id?: string | number | undefined; startTime?: string | undefined; endTime?: string | null | undefined; originalPath?: string | undefined; savePath?: string | undefined; fileSize?: string | number | undefined; fileType?: string | undefined; series?: string | undefined; episode?: string | undefined; }[] | undefined',
      description: '媒体列表',
    },
    series: {
      type: '{ id?: string | number | undefined; title?: string | undefined; path?: string | undefined; } | undefined',
      description: 'Sonarr系列信息',
    },
    missingEpisodes: {
      type: '{ seasonNumber?: string | number | undefined; episodeNumber?: string | number | undefined; title?: string | undefined; hasFile?: boolean | undefined; }[] | undefined',
      description: 'Sonarr缺失的集信息',
    },
  },
  QueryCondition: {
    fieldName: {
      type: 'string | undefined',
      description: '字段名',
    },
    fieldValue: {
      type: 'string | undefined',
      description: '字段值',
    },
    conditionalType: {
      type: 'number | undefined',
      description: '条件类型',
    },
    cSharpTypeName: {
      type: 'string | undefined',
      description: 'CSharp类型名',
    },
  },
  QueryDto: {
    pageNumber: {
      type: 'string | number | undefined',
      description: '页数',
      format: 'int32',
    },
    pageSize: {
      type: 'string | number | undefined',
      description: '每页大小',
      format: 'int32',
    },
    condition: {
      type: '{ fieldName?: string | undefined; fieldValue?: string | undefined; conditionalType?: number | undefined; cSharpTypeName?: string | undefined; }[] | null | undefined',
      description: '查询条件',
    },
    order: {
      type: '{ fieldName?: string | undefined; orderByType?: number | undefined; }[] | null | undefined',
      description: '排序条件',
    },
  },
  QueryOrder: {
    fieldName: {
      type: 'string | undefined',
      description: '字段名',
    },
    orderByType: {
      type: 'number | undefined',
      description: '排序类型',
    },
  },
  RenamePreview: {
    oldName: {
      type: 'string | undefined',
      description: '原文件名',
    },
    newName: {
      type: 'string | undefined',
      description: '新文件名',
    },
    status: {
      type: 'string | undefined',
      description: '状态',
    },
  },
  RenameRequest: {
    targetDir: {
      type: 'string | undefined',
      description: '目标目录',
    },
    extensions: {
      type: 'string[] | undefined',
      description: '需要重命名的文件扩展名列表，例如 [".mp4", ".mkv"]',
    },
    regexPattern: {
      type: 'string | undefined',
      description: '用于提取剧集信息的正则表达式',
    },
    offset: {
      type: 'string | number | undefined',
      description: '集数偏移量',
      format: 'int32',
    },
    template: {
      type: 'string | undefined',
      description: '重命名模板，使用 {ep} 作为集数占位符，例如 "Anime_E{ep}"',
    },
    padding: {
      type: 'string | number | undefined',
      description: '集数填充位数，例如 2 表示集数 1 会被填充为 "01"',
      format: 'int32',
    },
  },
  SchemaAiRequest: {
    schema: {
      type: '{ typeName?: string | undefined; fields?: { name?: string | undefined; type?: string | undefined; description?: string | null | undefined; }[] | undefined; sampleData?: unknown; } | undefined',
      description: 'JSON Schema',
    },
    messages: {
      type: '{ role?: string | undefined; content?: string | undefined; }[] | undefined',
      description: '对话消息列表',
    },
  },
  SchemaField: {
    name: {
      type: 'string | undefined',
      description: '字段名称',
    },
    type: {
      type: 'string | undefined',
      description: '字段类型',
    },
    description: {
      type: 'string | null | undefined',
      description: '字段描述（可选）',
    },
  },
  SchemaInfo: {
    typeName: {
      type: 'string | undefined',
      description: '类型名称',
    },
    fields: {
      type: '{ name?: string | undefined; type?: string | undefined; description?: string | null | undefined; }[] | undefined',
      description: '字段列表',
    },
    sampleData: {
      type: 'unknown',
      description: '字段描述（可选）',
    },
  },
  SonarrEpisode: {
    seasonNumber: {
      type: 'string | number | undefined',
      description: '季',
      format: 'int32',
    },
    episodeNumber: {
      type: 'string | number | undefined',
      description: '集',
      format: 'int32',
    },
    title: {
      type: 'string | undefined',
      description: '标题',
    },
    hasFile: {
      type: 'boolean | undefined',
      description: '是否有文件',
    },
  },
  SonarrSeries: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int32',
    },
    title: {
      type: 'string | undefined',
      description: '标题',
    },
    path: {
      type: 'string | undefined',
      description: '路径',
    },
  },
  SystemController: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    controller: {
      type: 'string | undefined',
      description: '控制器',
    },
    title: {
      type: 'string | undefined',
      description: '标题',
    },
  },
  SystemRole: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    name: {
      type: 'string | undefined',
      description: '角色名',
    },
  },
  SystemUser: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    isPlatformAdmin: {
      type: 'boolean | undefined',
      description: '平台超管',
    },
    email: {
      type: 'string | undefined',
      description: '邮箱',
    },
    nickName: {
      type: 'string | undefined',
      description: '昵称',
    },
    password: {
      type: 'string | undefined',
      description: '密码',
    },
    role: {
      type: '(string | number)[] | undefined',
      description: '角色',
    },
  },
  Task: {
    id: {
      type: 'string | number | undefined',
      format: 'int32',
    },
    exception: {
      type: '{ innerExceptions?: { targetSite?: unknown; message?: string | null | undefined; data?: Record<string, never> | null | undefined; innerException?: any | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; }[] | null | undefined; message?: string | null | undefined; targetSite?: unknown; data?: Record<string, never> | null | undefined; innerException?: { targetSite?: unknown; message?: string | null | undefined; data?: Record<string, never> | null | undefined; innerException?: any | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; } | undefined; helpLink?: string | null | undefined; source?: string | null | undefined; hResult?: string | number | undefined; stackTrace?: string | null | undefined; } | undefined',
    },
    status: {
      type: 'number | undefined',
    },
    isCanceled: {
      type: 'boolean | undefined',
    },
    isCompleted: {
      type: 'boolean | undefined',
    },
    isCompletedSuccessfully: {
      type: 'boolean | undefined',
    },
    creationOptions: {
      type: 'number | undefined',
    },
    asyncState: {
      type: 'unknown',
    },
    isFaulted: {
      type: 'boolean | undefined',
    },
  },
  TaskCreationOptions: {},
  TaskStatus: {},
  UserVerifyType: {},
  demo: {
    ts: {
      type: 'string | undefined',
      description: '时间',
      format: 'date-time',
    },
  },
}

export type AggregateException = components['schemas']['AggregateException']
export type ChatMessage = components['schemas']['ChatMessage']
export type CollectedMedia = components['schemas']['CollectedMedia']
export type CoverageSeason = components['schemas']['CoverageSeason']
export type CustomConditionalType =
  components['schemas']['CustomConditionalType']
export type CustomOrderByType = components['schemas']['CustomOrderByType']
export type DanmuCoverage = components['schemas']['DanmuCoverage']
export type DownloadTask = components['schemas']['DownloadTask']
export type Exception = components['schemas']['Exception']
export type ExecuteRenameRequest = components['schemas']['ExecuteRenameRequest']
export type IFormFile = components['schemas']['IFormFile']
export type MessageCode = components['schemas']['MessageCode']
export type MessageCodeEnum = components['schemas']['MessageCodeEnum']
export type MethodBase = components['schemas']['MethodBase']
export type PagedResultOfCollectedMedia =
  components['schemas']['PagedResultOfCollectedMedia']
export type PendingSeries = components['schemas']['PendingSeries']
export type QueryCondition = components['schemas']['QueryCondition']
export type QueryDto = components['schemas']['QueryDto']
export type QueryOrder = components['schemas']['QueryOrder']
export type RenamePreview = components['schemas']['RenamePreview']
export type RenameRequest = components['schemas']['RenameRequest']
export type SchemaAiRequest = components['schemas']['SchemaAiRequest']
export type SchemaField = components['schemas']['SchemaField']
export type SchemaInfo = components['schemas']['SchemaInfo']
export type SonarrEpisode = components['schemas']['SonarrEpisode']
export type SonarrSeries = components['schemas']['SonarrSeries']
export type SystemController = components['schemas']['SystemController']
export type SystemRole = components['schemas']['SystemRole']
export type SystemUser = components['schemas']['SystemUser']
export type Task = components['schemas']['Task']
export type TaskCreationOptions = components['schemas']['TaskCreationOptions']
export type TaskStatus = components['schemas']['TaskStatus']
export type UserVerifyType = components['schemas']['UserVerifyType']
export type demo = generated['schemas']['demo']
