/**
 * This file is auto-generated by scripts/generateSchema.ts
 * Do not edit manually
 */
import { components as generated } from '@/api/generated'
import { components } from '@/api/schema'

/** Runtime representation of OpenAPI Schemas */
export const schemas = {
  ChatMessage: {
    role: {
      type: 'string | undefined',
      description: '角色 (user, assistant, system)',
    },
    content: {
      type: 'string | undefined',
      description: '内容',
    },
  },
  CollectedMedia: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    startTime: {
      type: 'string | undefined',
      description: '开始处理时间',
      format: 'date-time',
    },
    endTime: {
      type: 'string | null | undefined',
      description: '结束处理时间',
      format: 'date-time',
    },
    originalPath: {
      type: 'string | undefined',
      description: '原始路径',
    },
    savePath: {
      type: 'string | undefined',
      description: '保存路径',
    },
    fileSize: {
      type: 'string | number | undefined',
      description: '文件大小',
      format: 'int64',
    },
    fileType: {
      type: 'string | undefined',
      description: '文件类型',
    },
    series: {
      type: 'string | undefined',
      description: '系列',
    },
    episode: {
      type: 'string | undefined',
      description: '集数',
    },
  },
  CustomConditionalType: {},
  CustomOrderByType: {},
  IFormFile: {},
  MessageCode: {
    codeIndex: {
      type: 'string | undefined',
    },
    code: {
      type: 'string | undefined',
    },
    args: {
      type: 'unknown[] | null',
    },
    message: {
      type: 'string | undefined',
    },
  },
  MessageCodeEnum: {},
  PagedResultOfCollectedMedia: {
    items: {
      type: '{ id?: string | number | undefined; startTime?: string | undefined; endTime?: string | null | undefined; originalPath?: string | undefined; savePath?: string | undefined; fileSize?: string | number | undefined; fileType?: string | undefined; series?: string | undefined; episode?: string | undefined; }[]',
      description: '当前页的数据列表',
    },
    totalCount: {
      type: 'string | number',
      description: '数据总条数',
      format: 'int32',
    },
    pageNumber: {
      type: 'string | number',
      description: '当前页码',
      format: 'int32',
    },
    pageSize: {
      type: 'string | number',
      description: '每页大小',
      format: 'int32',
    },
    totalPages: {
      type: 'string | number | undefined',
      description: '总页数',
      format: 'int32',
    },
    hasPreviousPage: {
      type: 'boolean | undefined',
      description: '是否有上一页',
    },
    hasNextPage: {
      type: 'boolean | undefined',
      description: '是否有下一页',
    },
  },
  QueryCondition: {
    fieldName: {
      type: 'string | undefined',
      description: '字段名',
    },
    fieldValue: {
      type: 'string | undefined',
      description: '字段值',
    },
    conditionalType: {
      type: 'number | undefined',
      description: '条件类型',
    },
    cSharpTypeName: {
      type: 'string | undefined',
      description: 'CSharp类型名',
    },
  },
  QueryDto: {
    pageNumber: {
      type: 'string | number | undefined',
      description: '页数',
      format: 'int32',
    },
    pageSize: {
      type: 'string | number | undefined',
      description: '每页大小',
      format: 'int32',
    },
    condition: {
      type: '{ fieldName?: string | undefined; fieldValue?: string | undefined; conditionalType?: number | undefined; cSharpTypeName?: string | undefined; }[] | null | undefined',
      description: '查询条件',
    },
    order: {
      type: '{ fieldName?: string | undefined; orderByType?: number | undefined; }[] | null | undefined',
      description: '排序条件',
    },
  },
  QueryOrder: {
    fieldName: {
      type: 'string | undefined',
      description: '字段名',
    },
    orderByType: {
      type: 'number | undefined',
      description: '排序类型',
    },
  },
  SchemaAiRequest: {
    schema: {
      type: '{ typeName?: string | undefined; fields?: { name?: string | undefined; type?: string | undefined; description?: string | null | undefined; }[] | undefined; sampleData?: unknown; } | undefined',
      description: 'JSON Schema',
    },
    messages: {
      type: '{ role?: string | undefined; content?: string | undefined; }[] | undefined',
      description: '对话消息列表',
    },
  },
  SchemaField: {
    name: {
      type: 'string | undefined',
      description: '字段名称',
    },
    type: {
      type: 'string | undefined',
      description: '字段类型',
    },
    description: {
      type: 'string | null | undefined',
      description: '字段描述（可选）',
    },
  },
  SchemaInfo: {
    typeName: {
      type: 'string | undefined',
      description: '类型名称',
    },
    fields: {
      type: '{ name?: string | undefined; type?: string | undefined; description?: string | null | undefined; }[] | undefined',
      description: '字段列表',
    },
    sampleData: {
      type: 'unknown',
      description: '字段描述（可选）',
    },
  },
  SystemController: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    controller: {
      type: 'string | undefined',
      description: '控制器',
    },
    title: {
      type: 'string | undefined',
      description: '标题',
    },
  },
  SystemRole: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    name: {
      type: 'string | undefined',
      description: '角色名',
    },
  },
  SystemUser: {
    id: {
      type: 'string | number | undefined',
      description: 'ID',
      format: 'int64',
    },
    isPlatformAdmin: {
      type: 'boolean | undefined',
      description: '平台超管',
    },
    email: {
      type: 'string | undefined',
      description: '邮箱',
    },
    nickName: {
      type: 'string | undefined',
      description: '昵称',
    },
    password: {
      type: 'string | undefined',
      description: '密码',
    },
    role: {
      type: '(string | number)[] | undefined',
      description: '角色',
    },
  },
  UserVerifyType: {},
  demo: {
    ts: {
      type: 'string | undefined',
      description: '时间',
      format: 'date-time',
    },
  },
}

export type ChatMessage = components['schemas']['ChatMessage']
export type CollectedMedia = components['schemas']['CollectedMedia']
export type CustomConditionalType =
  components['schemas']['CustomConditionalType']
export type CustomOrderByType = components['schemas']['CustomOrderByType']
export type IFormFile = components['schemas']['IFormFile']
export type MessageCode = components['schemas']['MessageCode']
export type MessageCodeEnum = components['schemas']['MessageCodeEnum']
export type PagedResultOfCollectedMedia =
  components['schemas']['PagedResultOfCollectedMedia']
export type QueryCondition = components['schemas']['QueryCondition']
export type QueryDto = components['schemas']['QueryDto']
export type QueryOrder = components['schemas']['QueryOrder']
export type SchemaAiRequest = components['schemas']['SchemaAiRequest']
export type SchemaField = components['schemas']['SchemaField']
export type SchemaInfo = components['schemas']['SchemaInfo']
export type SystemController = components['schemas']['SystemController']
export type SystemRole = components['schemas']['SystemRole']
export type SystemUser = components['schemas']['SystemUser']
export type UserVerifyType = components['schemas']['UserVerifyType']
export type demo = generated['schemas']['demo']
