/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/Ai/Chat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 流式对话接口 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 对话历史列表 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["ChatMessage"][];
                    "text/json": components["schemas"]["ChatMessage"][];
                    "application/*+json": components["schemas"]["ChatMessage"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Ai/SchemaChat": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Schema AI 流式接口 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SchemaAiRequest"];
                    "text/json": components["schemas"]["SchemaAiRequest"];
                    "application/*+json": components["schemas"]["SchemaAiRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/SendVerifyCode": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 发送验证码 */
        post: {
            parameters: {
                query?: {
                    /** @description 验证方式 */
                    verifyType?: components["schemas"]["UserVerifyType"];
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 用户登录 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 登录信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/SetAvatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 设置用户头像 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "multipart/form-data": {
                        file?: components["schemas"]["IFormFile"];
                    };
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加角色 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemRole"];
                    "text/json": components["schemas"]["SystemRole"];
                    "application/*+json": components["schemas"]["SystemRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加用户 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 用户信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddRoleGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向角色授权控制器 */
        post: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number | string;
                    /** @description 控制器ID */
                    controllerId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/AddUserGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 向用户授权控制器 */
        post: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number | string;
                    /** @description 控制器ID */
                    controllerId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除角色 */
        delete: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户 */
        delete: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteRoleGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除角色授权 */
        delete: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: number | string;
                    /** @description 控制器ID */
                    controllerId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/DeleteUserGrant": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除用户授权 */
        delete: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: number | string;
                    /** @description 控制器ID */
                    controllerId?: number | string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/ModifyRole": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改角色 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 角色信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemRole"];
                    "text/json": components["schemas"]["SystemRole"];
                    "application/*+json": components["schemas"]["SystemRole"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/ModifyUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** 修改用户 */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 用户信息 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["SystemUser"];
                    "text/json": components["schemas"]["SystemUser"];
                    "application/*+json": components["schemas"]["SystemUser"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/GetKey": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取RSA公钥 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有用户列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemUser"][];
                        "application/json": components["schemas"]["SystemUser"][];
                        "text/json": components["schemas"]["SystemUser"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Roles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取所有角色列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemRole"][];
                        "application/json": components["schemas"]["SystemRole"][];
                        "text/json": components["schemas"]["SystemRole"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/UserControllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户控制器列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    userId?: string;
                    /** @description 是否授权 */
                    isGranted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/RoleControllers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取角色控制器列表 */
        get: {
            parameters: {
                query?: {
                    /** @description 角色ID */
                    roleId?: string;
                    /** @description 是否授权 */
                    isGranted?: boolean;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/CurrentUser": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取当前用户信息 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemUser"];
                        "application/json": components["schemas"]["SystemUser"];
                        "text/json": components["schemas"]["SystemUser"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/GetAvatar": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取用户头像 */
        get: {
            parameters: {
                query?: {
                    /** @description 用户ID */
                    id?: string;
                    /** @description token */
                    token?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/Granted": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取已授权的控制器 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["SystemController"][];
                        "application/json": components["schemas"]["SystemController"][];
                        "text/json": components["schemas"]["SystemController"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/RefreshToken": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 刷新token */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcLoginAddress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取OIDC登录地址 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string;
                        "application/json": string;
                        "text/json": string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcLogin": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC登录 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Authentication/OidcCallback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** OIDC回调处理 */
        get: {
            parameters: {
                query?: {
                    /** @description 回调中的授权码 */
                    code?: string;
                    /** @description 回调中的状态参数 */
                    state?: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Cleanup/DeleteSeriesTrash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除剧集目录垃圾 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Cleanup/DeleteSeriesSubtitleTrash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除剧集目录字幕垃圾 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Cleanup/SeriesTrash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 剧集目录垃圾 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string[];
                        "application/json": string[];
                        "text/json": string[];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Cleanup/SeriesSubtitleTrash": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 剧集目录字幕垃圾 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string[];
                        "application/json": string[];
                        "text/json": string[];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/Cleanup/MergeSubtitle": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 已合并的字幕文件 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": string[];
                        "application/json": string[];
                        "text/json": string[];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/AddDownloadTask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 添加下载任务 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CollectedMedia"][];
                    "text/json": components["schemas"]["CollectedMedia"][];
                    "application/*+json": components["schemas"]["CollectedMedia"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/AddCompleteTask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** 将媒体标记为已完成 */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CollectedMedia"][];
                    "text/json": components["schemas"]["CollectedMedia"][];
                    "application/*+json": components["schemas"]["CollectedMedia"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/DownloadTasks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取下载任务列表 */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["DownloadTask"][];
                        "application/json": components["schemas"]["DownloadTask"][];
                        "text/json": components["schemas"]["DownloadTask"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/PendingSeries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** 获取待处理的Series */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PendingSeries"][];
                        "application/json": components["schemas"]["PendingSeries"][];
                        "text/json": components["schemas"]["PendingSeries"][];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/RemoveCompleteTask": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** 删除已完成的任务记录 */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CollectedMedia"][];
                    "text/json": components["schemas"]["CollectedMedia"][];
                    "application/*+json": components["schemas"]["CollectedMedia"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/Insert": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 添加数据
         * @description 批量添加数据
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CollectedMedia"][];
                    "text/json": components["schemas"]["CollectedMedia"][];
                    "application/*+json": components["schemas"]["CollectedMedia"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": (number | string)[];
                        "application/json": (number | string)[];
                        "text/json": (number | string)[];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/Delete": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * 删除数据
         * @description 批量删除数据
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CollectedMedia"][];
                    "text/json": components["schemas"]["CollectedMedia"][];
                    "application/*+json": components["schemas"]["CollectedMedia"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/Update": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * 更新数据
         * @description 批量更新数据
         */
        put: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": components["schemas"]["CollectedMedia"][];
                    "text/json": components["schemas"]["CollectedMedia"][];
                    "application/*+json": components["schemas"]["CollectedMedia"][];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/Query": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 查询列表
         * @description 按照条件和排序方式查询数据列表
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["PagedResultOfCollectedMedia"];
                        "application/json": components["schemas"]["PagedResultOfCollectedMedia"];
                        "text/json": components["schemas"]["PagedResultOfCollectedMedia"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/Count": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 统计总数
         * @description 按照条件统计数据总数
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": number | string;
                        "application/json": number | string;
                        "text/json": number | string;
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/CollectMedia/DownloadExcel": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 下载Excel
         * @description 按照条件和排序方式将数据导出为Excel文件
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description 查询条件 */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["QueryDto"];
                    "text/json": components["schemas"]["QueryDto"];
                    "application/*+json": components["schemas"]["QueryDto"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "text/plain": components["schemas"]["MessageCode"];
                        "application/json": components["schemas"]["MessageCode"];
                        "text/json": components["schemas"]["MessageCode"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        AggregateException: {
            innerExceptions?: null | components["schemas"]["Exception"][];
            message?: null | string;
            targetSite?: components["schemas"]["MethodBase"];
            data?: null | Record<string, never>;
            innerException?: components["schemas"]["Exception"];
            helpLink?: null | string;
            source?: null | string;
            /** Format: int32 */
            hResult?: number | string;
            stackTrace?: null | string;
        };
        /** @description 聊天消息模型 */
        ChatMessage: {
            /** @description 角色 (user, assistant, system) */
            role?: string;
            /** @description 内容 */
            content?: string;
        };
        /** @description 已处理媒体 */
        CollectedMedia: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /**
             * Format: date-time
             * @description 开始处理时间
             */
            startTime?: string;
            /**
             * Format: date-time
             * @description 结束处理时间
             */
            endTime?: null | string;
            /** @description 原始路径 */
            originalPath?: string;
            /** @description 保存路径 */
            savePath?: string;
            /**
             * Format: int64
             * @description 文件大小
             */
            fileSize?: number | string;
            /** @description 文件类型 */
            fileType?: string;
            /** @description 系列 */
            series?: string;
            /** @description 集数 */
            episode?: string;
        };
        /**
         * @description 条件类型
         *
         *     | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | Equal |
         *     | 1 | Like |
         *     | 2 | GreaterThan |
         *     | 3 | GreaterThanOrEqual |
         *     | 4 | LessThan |
         *     | 5 | LessThanOrEqual |
         *     | 6 | In |
         *     | 7 | NotIn |
         *     | 8 | LikeLeft |
         *     | 9 | LikeRight |
         *     | 10 | NoEqual |
         *     | 11 | IsNullOrEmpty |
         *     | 12 | IsNotNullOrEmpty |
         *     | 13 | NoLike |
         *     | 14 | EqualNull |
         *     | 15 | InLike |
         *     | 16 | Range |
         */
        CustomConditionalType: number;
        /**
         * @description 排序类型
         *
         *     | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | Asc |
         *     | 1 | Desc |
         */
        CustomOrderByType: number;
        /** @description 下载任务 */
        DownloadTask: {
            /** @description 媒体信息 */
            media: components["schemas"]["CollectedMedia"];
            series?: null | components["schemas"]["SonarrSeries"];
            currentTask?: null | components["schemas"]["Task"];
            /** @description 任务状态 */
            status?: components["schemas"]["TaskStatus"];
            /**
             * Format: double
             * @description 下载进度
             * @default 0
             */
            progress: number | string;
        };
        Exception: {
            targetSite?: components["schemas"]["MethodBase"];
            message?: null | string;
            data?: null | Record<string, never>;
            innerException?: components["schemas"]["Exception"];
            helpLink?: null | string;
            source?: null | string;
            /** Format: int32 */
            hResult?: number | string;
            stackTrace?: null | string;
        };
        /** Format: binary */
        IFormFile: string;
        MessageCode: {
            codeIndex?: components["schemas"]["MessageCodeEnum"];
            code?: string;
            args: null | unknown[];
            message?: string;
        };
        /**
         * @description | 枚举值 | 描述 |
         *     |------|------|
         *     | Unauthorized | 无权限访问 |
         *     | FileEmpty | 文件不能为空 |
         *     | FileSizeLimit | 文件不能超过{0} |
         *     | ParamError | 参数错误: {0} |
         *     | ExportDataEmpty | 导出数据为空 |
         *     | ExcelExportFailed | 生成Excel文件失败 |
         *     | RegisterNotOpen | 暂未开放公开注册，如需注册请联系管理员 |
         *     | AccountRequired | 验证账号不能为空 |
         *     | EmailFormatError | 邮箱格式错误 |
         *     | EmailExists | 该邮箱已被注册 |
         *     | VerifyCodeFrequent | 发送验证码过于频繁，请稍后再试 |
         *     | VerifyCodeLimit | 一小时内最多发送{0}次验证码，请稍后再试 |
         *     | UserNotFound | 用户不存在 |
         *     | PasswordError | 密码或验证码错误 |
         *     | NoPermissionAction | 没有权限进行此操作: {0} |
         *     | EntityExists | 该记录已存在 |
         *     | DecryptError | 解密失败 |
         *     | InvalidEntity | 包含无效的标识: {0} |
         *     | GrantExists | 该授权已存在 |
         *     | GrantNotFound | 该授权不存在 |
         *     | DeleteSelfForbidden | 禁止删除当前登录用户 |
         *     | RoleNotFound | 角色不存在 |
         *     | ControllerNotFound | 控制器不存在 |
         *     | TokenInvalidOrExpired | token无效或已过期 |
         *     | InvalidId | 无效的ID |
         *     | AvatarNotFound | 用户未设置头像 |
         *     | WebDavQueryFailed | WebDav查询失败 |
         *     | TaskExists | 该任务已存在: {0} |
         *     | FileExists | 该文件正在下载或已下载: {0} |
         *     | MediaExists | 该媒体已存在: {0} |
         *     | SeriesNotExists | 该剧集目录不存在: {0} |
         */
        MessageCodeEnum: string;
        MethodBase: unknown;
        /** @description 通用分页响应结果 */
        PagedResultOfCollectedMedia: {
            /** @description 当前页的数据列表 */
            items: components["schemas"]["CollectedMedia"][];
            /**
             * Format: int32
             * @description 数据总条数
             */
            totalCount: number | string;
            /**
             * Format: int32
             * @description 当前页码
             */
            pageNumber: number | string;
            /**
             * Format: int32
             * @description 每页大小
             */
            pageSize: number | string;
            /**
             * Format: int32
             * @description 总页数
             */
            totalPages?: number | string;
            /** @description 是否有上一页 */
            hasPreviousPage?: boolean;
            /** @description 是否有下一页 */
            hasNextPage?: boolean;
        };
        /** @description 待处理系列信息 */
        PendingSeries: {
            /** @description 媒体列表 */
            medias?: components["schemas"]["CollectedMedia"][];
            /** @description Sonarr系列信息 */
            series?: components["schemas"]["SonarrSeries"];
            /** @description Sonarr缺失的集信息 */
            missingEpisodes?: components["schemas"]["SonarrEpisode"][];
        };
        QueryCondition: {
            /** @description 字段名 */
            fieldName?: string;
            /** @description 字段值 */
            fieldValue?: string;
            /** @description 条件类型 */
            conditionalType?: components["schemas"]["CustomConditionalType"];
            /** @description CSharp类型名 */
            cSharpTypeName?: string;
        };
        /** @description 查询参数 */
        QueryDto: {
            /**
             * Format: int32
             * @description 页数
             */
            pageNumber?: number | string;
            /**
             * Format: int32
             * @description 每页大小
             */
            pageSize?: number | string;
            /** @description 查询条件 */
            condition?: null | components["schemas"]["QueryCondition"][];
            /** @description 排序条件 */
            order?: null | components["schemas"]["QueryOrder"][];
        };
        QueryOrder: {
            /** @description 字段名 */
            fieldName?: string;
            /** @description 排序类型 */
            orderByType?: components["schemas"]["CustomOrderByType"];
        };
        /** @description Schema AI 请求模型 */
        SchemaAiRequest: {
            /** @description JSON Schema */
            schema?: components["schemas"]["SchemaInfo"];
            /** @description 对话消息列表 */
            messages?: components["schemas"]["ChatMessage"][];
        };
        /** @description Schema 字段模型 */
        SchemaField: {
            /** @description 字段名称 */
            name?: string;
            /** @description 字段类型 */
            type?: string;
            /** @description 字段描述（可选） */
            description?: null | string;
        };
        /** @description Schema 信息模型 */
        SchemaInfo: {
            /** @description 类型名称 */
            typeName?: string;
            /** @description 字段列表 */
            fields?: components["schemas"]["SchemaField"][];
            /** @description 字段描述（可选） */
            sampleData?: unknown;
        };
        /** @description Sonarr集 */
        SonarrEpisode: {
            /**
             * Format: int32
             * @description 季
             */
            seasonNumber?: number | string;
            /**
             * Format: int32
             * @description 集
             */
            episodeNumber?: number | string;
            /** @description 标题 */
            title?: string;
            /** @description 是否有文件 */
            hasFile?: boolean;
        };
        /** @description Sonarr系列 */
        SonarrSeries: {
            /**
             * Format: int32
             * @description ID
             */
            id?: number | string;
            /** @description 标题 */
            title?: string;
            /** @description 路径 */
            path?: string;
        };
        /** @description 系统控制器 */
        SystemController: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /** @description 控制器 */
            controller?: string;
            /** @description 标题 */
            title?: string;
        };
        /** @description 系统角色 */
        SystemRole: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /** @description 角色名 */
            name?: string;
        };
        /** @description 系统用户 */
        SystemUser: {
            /**
             * Format: int64
             * @description ID
             */
            id?: number | string;
            /** @description 平台超管 */
            isPlatformAdmin?: boolean;
            /** @description 邮箱 */
            email?: string;
            /** @description 昵称 */
            nickName?: string;
            /** @description 密码 */
            password?: string;
            /** @description 角色 */
            role?: (number | string)[];
        };
        Task: {
            /** Format: int32 */
            id?: number | string;
            exception?: components["schemas"]["AggregateException"];
            status?: components["schemas"]["TaskStatus"];
            isCanceled?: boolean;
            isCompleted?: boolean;
            isCompletedSuccessfully?: boolean;
            creationOptions?: components["schemas"]["TaskCreationOptions"];
            asyncState?: unknown;
            isFaulted?: boolean;
        };
        /**
         * @description | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | None |
         *     | 1 | PreferFairness |
         *     | 2 | LongRunning |
         *     | 4 | AttachedToParent |
         *     | 8 | DenyChildAttach |
         *     | 16 | HideScheduler |
         *     | 64 | RunContinuationsAsynchronously |
         */
        TaskCreationOptions: number;
        /**
         * @description | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | Created |
         *     | 1 | WaitingForActivation |
         *     | 2 | WaitingToRun |
         *     | 3 | Running |
         *     | 4 | WaitingForChildrenToComplete |
         *     | 5 | RanToCompletion |
         *     | 6 | Canceled |
         *     | 7 | Faulted |
         */
        TaskStatus: number;
        /**
         * @description | 枚举值 | 描述 |
         *     |------|------|
         *     | 0 | 邮箱 |
         */
        UserVerifyType: number;
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
